### ISSUE TITLE
allow other hosts to send udp messages

### ISSUE THREAD

**Issue by micuat** [munshkr/hydra-superdirt#1]
hey, thanks for the cool package!

we noticed that this doesn't work across computers over network (intranet). This is because here

https://github.com/munshkr/hydra-superdirt/blob/main/bin/hydra-sc-bridge.js#L21

`options.udpServer.host` has to be set to the IP address of the interface - or `0.0.0.0` in order to allow any host to connect. Perhaps the latter would be useful:

```javascript
    udpServer: { port: options.oscPort, host: "0.0.0.0" },
```

reference: https://adzialocha.github.io/osc-js/class/src/plugin/bridge.js~BridgePlugin.html#instance-method-open

**Comment by munshkr** [comment]
Thanks for the tip!!
